version: '3.8'

services:
  traefik:
    image: traefik:v2.4
    command:
      - --api.insecure=true
      - --providers.file.filename=/etc/traefik/providers/dynamic.yaml
      - --providers.file.watch=true
      - --entrypoints.web.address=:12000
    ports:
      - "12000:12000"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik_providers:/etc/traefik/providers