@Eventool.Api_HostAddress = http://localhost:5015

POST {{Eventool.Api_HostAddress}}/api/auth/sign-up
Accept: application/json
Content-Type: application/json

{
  "fullName": "F",
  "email": "test4@email.com",
  "password": "1234Admin!"
}

###

POST {{Eventool.Api_HostAddress}}/api/auth/sign-in
Accept: application/json
Content-Type: application/json

{
  "fullName": "Test test",
  "email": "test4@email.com",
  "password": "1234Admin!"
}